### ISSUE TITLE
[Question] Customizing bombinhas with other music, image/tiles and so forth, as a "game-engine"?

### ISSUE THREAD

**Issue by rubyFeedback** [victords/super-bombinhas#2]
Hey there victords,

First - super-bombinhas is really nice; not too easy, playable from the get go,
no bugs that I could find.

I was, however had, thinking of adjusting the game style a bit into a RPG
setting ... like a bit more of an arcade style with a bit of a story. The game
world I would use was by my old pen and paper roleplaying group.

Anyway. What I am trying to say is ... it would be neat if we could
sort of re-define bombinhas as-is. Different sprites/images, different
music and what. I can modify the code as-is, but I wondered if it
may be possible to extend bombinhas itself, perhaps by making
it more flexible to load the whole dataset, e. g. a yaml file or something.

I am not sure if it is worth it the time investment to change it; we have
hardcoded paths such as:

    @scenes << Res.img("movie_#{f.split('/')[-1].chomp('.png')}")

But if it were able to customize the dataset for bombinhas that would
be quite nice.

My idea would be to not just do this alone but to also change the
playing a bit, e. g. allow for sword fighting, a bit like the old
prince of persia if you know that DOS game. But, I also plan
to keep it super-simple, so really this is more a question in
regards as to how customizable super-bombinhas could be
made. Anyway, feel free to close this - it's more a question
and suggestion really. :)

(Reason why I think a "game engine" would be better is because
that way we could just customize it, rather than write one anew.
In ruby-gosu in particular I noticed that people rarely share and
exchange code and instead everyone writes things anew, de-novo)

**Comment by victords** [comment]
Hi @rubyFeedback,

I'm glad to hear you liked the game!

I also found your suggestion quite interesting. However, I now want to focus on advertising the game so that more people get to know it and play it... Otherwise, all the effort to make it an awesome game (and, perhaps, a customizable game or game engine) would be kind of in vain... I'm struggling a bit with the advertising part, I needed to create a trailer for it to make it more attractive, publish it to Steam and maybe other platforms, and so on, so I don't have much time to dedicate to extend it further... The level editor itself was an extra feature that I didn't plan initially to include, but if nobody sees the game and uses it, it's not worth the effort, right?

Anyways, if you do have the time, feel free to fork the project and adapt it to what you're suggesting, I guess it's perfectly doable. The level editor could be a starting point, by allowing to load custom images, songs and then, with some sort of scripting system, custom objects and enemies too...

Oh, and if you have some suggestions on how to better advertise the game, I'd be happy to hear them. :)
